[build]
  command = "pip install -r requirements.txt && gunicorn app:app"  # Install dependencies and run Flask with Gunicorn
  publish = "/"  # Root directory for Flask app (ensure your static files are served)

[functions]
  directory = "functions"  # Specify serverless function directory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
